### ISSUE TITLE
Ориентация D2

### ISSUE THREAD

**Issue by vladimirgamalyan** [Nordic-Energy/UsbToUartConverter#1]
Не смог найти пометки у первого вывода микросхемы D2 или другой информации на плате, чтобы правильно спозиционировать микросхему при ручном монтаже (на слоях меди и шелкографии, на мех. слое вижу).

**Comment by Nordic-Energy** [comment]
В проекте AD есть слой Top Assembly, который содержит в себе информацию для сборочного чертежа. Перейдите в слой Top Assembly и нажмите Shift+S, вы увидите отображение первого вывода у микросхем. 

В ближайшее время я так же проверю проект и выгружу из него документацию, в том числе и сборочный чертеж.
