### ISSUE TITLE
Ориентация светодиодов

### ISSUE THREAD

**Issue by vladimirgamalyan** [Nordic-Energy/UsbToUartConverter#2]
На плате нет визуальной информации какой полярностью впаивать светодиоды при ручном монтаже. При автоматическом монтаже, если использовать угол поворота из проекта, получается некорректное позиционирование (при 0 градусов машины ожидают как правило [слева катод](https://ohm.bu.edu/~pbohn/__Engineering_Reference/pcb_layout/pcbmatrix/Component%20Zero%20Orientations%20for%20CAD%20Libraries.pdf)).

**Comment by Nordic-Energy** [comment]
На корпусе 0603 адекватным способом показать катод является точка, но из-за плотности установки компонентов на нее не хватило места. Учитывая, что есть сборочный чертеж и слой top assembly, то отмечать на шелкографии смысла не вижу. 

Под автомат данный проект точно не заточен, но при необходимости можно сгенерировать pick and place file из альтиума и этого будет достаточно, чтобы CAM в P&P смог понять как устанавливать компонент.

Если хочется именно катод слева, то библиотека и проект открыты, вы можете сделать по своему и сделать пул реквест, я его приму.
